shamefullyHoist: true

shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - tinyexec@1.2.2
  - tinyclip@0.1.13

allowBuilds:
  simple-git-hooks: true
  sqlite3: true
